git pusversion: '3'
services:

  database:
    image: postgres:12-alpine
    container_name: 'iot-device-manager-postgres'
    environment:
      POSTGRES_USER: 'iot-device-manager'
      POSTGRES_DB: 'iot-device-manager'
      POSTGRES_PASSWORD: 'password'
    ports:
      - "5432:5432"

  rabbitmq:
    build: images/rabbitmq
    container_name: 'iot-device-manager-rabbitmq'
    environment:
      RABBITMQ_DEFAULT_USER: 'admin'
      RABBITMQ_DEFAULT_PASS: 'password'
      RABBITMQ_DEFAULT_VHOST: 'iot-device-manager'
    ports:
      - "5672:5672"
      - "15672:15672"