---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbit-conf
  namespace: iot-device-manager
data:
  host: rabbitmq
  vhost: iot-device-manager
---
apiVersion: v1
kind: Secret
metadata:
  name: rabbit-credentials
  namespace: iot-device-manager
data:
  rabbit_user: YWRtaW4=
  rabbit_password: cGFzc3dvcmQ=
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: rabbitmq
  name: rabbitmq
  namespace: iot-device-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - image: dpilipovic98/iot-device-manager-rabbitmq
          name: rabbitmq
          ports:
            - containerPort: 5672
              name: amqp
            - containerPort: 15672
              name: http
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: rabbitmq
  name: rabbitmq
  namespace: iot-device-manager
spec:
  ports:
    - port: 5672
      targetPort: 5672
      name: amqp
    - port: 15672
      targetPort: 15672
      name: http
  selector:
    app: rabbitmq