management.endpoints.web.base-path: /device-mock/actuator

spring.datasource:
  driver-class-name: org.postgresql.Driver
  url: jdbc:postgresql://${DB_HOST}:5432/${DB_NAME}
  username: ${POSTGRES_USER}
  password: ${POSTGRES_PASSWORD}

spring.rabbitmq:
  host: rabbitmq
  port: 5672
  virtual-host: iot-device-manager
  username: admin
  password: password
  listener.simple.concurrency: 1
