server:
  error:
    include-message: always
    include-binding-errors: always

server.port: 8180

management:
  endpoints.web.exposure.include: health, info, prometheus
  endpoint.health.probes.enabled: true