---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - port: {{ .Values.applicationPort }}
      targetPort: {{ .Values.applicationPort }}
  selector:
    app: {{ .Chart.Name }}