---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
  namespace: {{ .Values.namespace }}
data:
  postgres_user: {{ (.Values.postgres).user }}
  postgres_password: {{ (.Values.postgres).user }}