---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Chart.Name }}
    tier: database
spec:
  ports:
    - port: 5432
  selector:
    app: {{ .Chart.Name }}
    tier: database
  clusterIP: None