---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: api-application
  name: api-application
  namespace: iot-device-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-application
  template:
    metadata:
      labels:
        app: api-application
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/api-application/actuator/prometheus"
        prometheus.io/scheme: "http"
    spec:
      containers:
        - image: dpilipovic98/iot-device-manager-api:0.0.7-SNAPSHOT
          name: api-application-application
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: k8s
            - name: TZ
              value: Europe/Zagreb
            - name: JAVA_TOOL_OPTIONS
              value: -XX:MaxRAMPercentage=90 -XX:InitialRAMPercentage=80 -XX:MinRAMPercentage=70
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-conf
                  key: host
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: postgres-conf
                  key: name
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: postgres_user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: postgres_password
          resources:
            requests:
              memory: "250Mi"
              cpu: "250m"
            limits:
              memory: "500Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /api-application/actuator/health/liveness
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 20
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /api-application/actuator/health/readiness
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 20
            failureThreshold: 5
---
apiVersion: v1
kind: Service
metadata:
  name: api-application
  namespace: iot-device-manager
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: api-application
