management.endpoints.web.base-path: /message-processor/actuator

spring.datasource:
  url: jdbc:postgresql://${DB_HOST}:5432/${DB_NAME}
  username: ${POSTGRES_USER}
  password: ${POSTGRES_PASSWORD}

spring.rabbitmq:
  host: rabbitmq
  port: 5672
  virtual-host: iot-device-manager
  username: admin
  password: password
  listener.simple.concurrency: 1

mock.device.base.url: http://mock-device:8180/mock/device/