spring.datasource:
  url: jdbc:postgresql://localhost:5432/iot-device-manager?ApplicationName=message-processor
  username: iot-device-manager
  password: password

spring.rabbitmq:
  addresses: localhost
  virtual-host: iot-device-manager
  username: admin
  password: password

mock.device.base.url: http://localhost:8180/mock/device/
