management.endpoints.web.base-path: /message-processor/actuator

spring.datasource:
  driver-class-name: org.postgresql.Driver
  url: jdbc:postgresql://${DB_HOST}:5432/${DB_NAME}
  username: ${POSTGRES_USER}
  password: ${POSTGRES_PASSWORD}

spring.rabbitmq:
  host: ${RABBIT_HOST}
  port: 5672
  virtual-host: ${RABBIT_VHOST}
  username: ${RABBIT_USER}
  password: ${RABBIT_PASSWORD}
  listener.simple.concurrency: 1

mock.device.base.url: http://device-mock:8180/mock/device/