spring.datasource:
  url: jdbc:postgresql://database:5432/iot-device-manager?ApplicationName=message-processor
  username: iot-device-manager
  password: password

spring.rabbitmq:
  host: rabbitmq
  port: 5672
  virtual-host: iot-device-manager
  username: admin
  password: password
  listener.simple.concurrency: 1

mock.device.base.url: http://device-mock:8180/mock/device/